CREATE PROCEDURE LOGIN_ACESSO_SPU 
    @LOGIN_ACESSO_ID INT = NULL, 
    @REGISTRO_LOGIN_ID INT = NULL, 
    @TOKEN VARCHAR(64)  = NULL, 
    @IP VARCHAR(40)  = NULL, 
    @DATA_INCLUSAO SMALLDATETIME = NULL, 
    @DATA_VALIDADE SMALLDATETIME = NULL 
AS BEGIN 
    UPDATE 
        A 
    SET 
        REGISTRO_LOGIN_ID = ISNULL(@REGISTRO_LOGIN_ID, REGISTRO_LOGIN_ID), 
        TOKEN = ISNULL(@TOKEN, TOKEN), 
        IP = ISNULL(@IP, IP), 
        DATA_INCLUSAO = ISNULL(@DATA_INCLUSAO, DATA_INCLUSAO), 
        DATA_VALIDADE = ISNULL(@DATA_VALIDADE, DATA_VALIDADE) 
    FROM 
        LOGIN_ACESSO_TB A 
    WHERE 
        A.LOGIN_ACESSO_ID = ISNULL(@LOGIN_ACESSO_ID, A.LOGIN_ACESSO_ID) 

    EXEC LOGIN_ACESSO_SPS @LOGIN_ACESSO_ID 
END 
