CREATE PROCEDURE LOGIN_ATRIBUICAO_SPD 
    @LOGIN_ATRIBUICAO_ID INT = NULL 
AS BEGIN 
    DELETE A FROM 
        LOGIN_ATRIBUICAO_TB A 
    WHERE 
        LOGIN_ATRIBUICAO_ID = ISNULL(@LOGIN_ATRIBUICAO_ID, A.LOGIN_ATRIBUICAO_ID) 
END 
