CREATE PROCEDURE LOGIN_ATRIBUICAO_SPU 
    @LOGIN_ATRIBUICAO_ID INT = NULL, 
    @REGISTRO_LOGIN_ID INT = NULL, 
    @LOGIN_GRUPO_ID INT = NULL, 
    @LOGIN_PERFIL_ID INT = NULL 
AS BEGIN 
    UPDATE 
        A 
    SET 
        REGISTRO_LOGIN_ID = ISNULL(@REGISTRO_LOGIN_ID, REGISTRO_LOGIN_ID), 
        LOGIN_GRUPO_ID = ISNULL(@LOGIN_GRUPO_ID, LOGIN_GRUPO_ID), 
        LOGIN_PERFIL_ID = ISNULL(@LOGIN_PERFIL_ID, LOGIN_PERFIL_ID) 
    FROM 
        LOGIN_ATRIBUICAO_TB A 
    WHERE 
        A.LOGIN_ATRIBUICAO_ID = ISNULL(@LOGIN_ATRIBUICAO_ID, A.LOGIN_ATRIBUICAO_ID) 

    EXEC LOGIN_ATRIBUICAO_SPS @LOGIN_ATRIBUICAO_ID 
END 
