CREATE PROCEDURE LOGIN_SPD 
    @REGISTRO_LOGIN_ID INT = NULL 
AS BEGIN 
    DELETE A FROM 
        LOGIN_TB A 
    WHERE 
        REGISTRO_LOGIN_ID = ISNULL(@REGISTRO_LOGIN_ID, A.REGISTRO_LOGIN_ID) 
END 
