CREATE PROCEDURE LOGIN_SPU 
    @REGISTRO_LOGIN_ID INT = NULL, 
    @PESSOA_ID INT = NULL, 
    @USUARIO VARCHAR(50)  = NULL, 
    @SENHA VARCHAR(500)  = NULL 
AS BEGIN 
    UPDATE 
        A 
    SET 
        PESSOA_ID = ISNULL(@PESSOA_ID, PESSOA_ID), 
        USUARIO = ISNULL(@USUARIO, USUARIO), 
        SENHA = ISNULL(@SENHA, SENHA) 
    FROM 
        LOGIN_TB A 
    WHERE 
        A.REGISTRO_LOGIN_ID = ISNULL(@REGISTRO_LOGIN_ID, A.REGISTRO_LOGIN_ID) 

    EXEC LOGIN_SPS @REGISTRO_LOGIN_ID 
END 
