CREATE TABLE [dbo].[LOGIN_ACESSO_TB](
	[LOGIN_ACESSO_ID] [INT] IDENTITY(1,1) NOT NULL,
	[REGISTRO_LOGIN_ID] [INT] NOT NULL,
	[TOKEN] [VARCHAR](64) NOT NULL,
	[IP] [VARCHAR](40) NOT NULL,
	[DATA_INCLUSAO] SMALLDATETIME NULL,
	[DATA_VALIDADE] SMALLDATETIME NULL,
	CONSTRAINT [PK_LOGIN_ACESSO_TB] PRIMARY KEY CLUSTERED (
		[LOGIN_ACESSO_ID] ASC
	) WITH (
		PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON
	) ON [PRIMARY],
	CONSTRAINT FK_LOGIN_ACESSO_1 FOREIGN KEY (REGISTRO_LOGIN_ID) REFERENCES LOGIN_TB (REGISTRO_LOGIN_ID)
) ON [PRIMARY]
GO