CREATE TABLE [dbo].[LOGIN_TB](
	[REGISTRO_LOGIN_ID] [INT] IDENTITY(1,1) NOT NULL,
	[PESSOA_ID] [INT] NOT NULL,
	[USUARIO] [VARCHAR](50) NOT NULL,
	[SENHA] [VARCHAR](500) NULL,
	CONSTRAINT [PK_LOGIN_TB] PRIMARY KEY CLUSTERED (
		[REGISTRO_LOGIN_ID] ASC
	) WITH (
		PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON
	) ON [PRIMARY],
	CONSTRAINT FK_LOGIN_1 FOREIGN KEY (PESSOA_ID) REFERENCES PESSOA_TB (PESSOA_ID)
) ON [PRIMARY]
GO