CREATE PROCEDURE LOGIN_SPS 
    @REGISTRO_LOGIN_ID INT = NULL, 
    @PESSOA_ID INT = NULL,
	@USUARIO VARCHAR(100) = NULL
AS BEGIN 
    SELECT 
        A.REGISTRO_LOGIN_ID, 
        A.PESSOA_ID, 
        A.USUARIO, 
        A.SENHA 
    FROM 
        LOGIN_TB A 
    WHERE 
        A.REGISTRO_LOGIN_ID = ISNULL(@REGISTRO_LOGIN_ID, A.REGISTRO_LOGIN_ID) 
        AND A.PESSOA_ID = ISNULL(@PESSOA_ID, A.PESSOA_ID)
		AND A.USUARIO = ISNULL(@USUARIO, A.USUARIO)
END 
