CREATE PROCEDURE LOGIN_GRUPO_SPU 
    @LOGIN_GRUPO_ID INT = NULL, 
    @NOME VARCHAR(50)  = NULL, 
    @DESCRICAO VARCHAR(500)  = NULL, 
    @DATA_INCLUSAO SMALLDATETIME = NULL, 
    @DATA_ALTERACAO SMALLDATETIME = NULL 
AS BEGIN 
 
    SET @DATA_ALTERACAO = ISNULL(@DATA_ALTERACAO, GETDATE()); 
 
    UPDATE 
        A 
    SET 
        NOME = ISNULL(@NOME, NOME), 
        DESCRICAO = @DESCRICAO, 
        DATA_INCLUSAO = ISNULL(@DATA_INCLUSAO, DATA_INCLUSAO), 
        DATA_ALTERACAO = @DATA_ALTERACAO 
    FROM 
        LOGIN_GRUPO_TB A 
    WHERE 
        A.LOGIN_GRUPO_ID = ISNULL(@LOGIN_GRUPO_ID, A.LOGIN_GRUPO_ID)

    EXEC LOGIN_GRUPO_SPS @LOGIN_GRUPO_ID 
END 
