CREATE PROCEDURE LOGIN_GRUPO_SPS 
    @LOGIN_GRUPO_ID INT = NULL 
AS BEGIN 
    SELECT 
        A.LOGIN_GRUPO_ID, 
        A.NOME, 
        A.DESCRICAO, 
        A.DATA_INCLUSAO, 
        A.DATA_ALTERACAO 
    FROM 
        LOGIN_GRUPO_TB A 
    WHERE 
        A.LOGIN_GRUPO_ID = ISNULL(@LOGIN_GRUPO_ID, A.LOGIN_GRUPO_ID) 
END 
