CREATE PROCEDURE LOGIN_PERFIL_SPD 
    @LOGIN_PERFIL_ID INT = NULL 
AS BEGIN 
    DELETE A FROM 
        LOGIN_PERFIL_TB A 
    WHERE 
        LOGIN_PERFIL_ID = ISNULL(@LOGIN_PERFIL_ID, A.LOGIN_PERFIL_ID) 
END 
