CREATE PROCEDURE LOGIN_PERFIL_SPU 
    @LOGIN_PERFIL_ID INT = NULL, 
    @NOME VARCHAR(50)  = NULL, 
    @DESCRICAO VARCHAR(500)  = NULL, 
    @DATA_INCLUSAO SMALLDATETIME = NULL, 
    @DATA_ALTERACAO SMALLDATETIME = NULL 
AS BEGIN 
 
    SET @DATA_ALTERACAO = ISNULL(@DATA_ALTERACAO, GETDATE()); 
 
    UPDATE 
        A 
    SET 
        NOME = ISNULL(@NOME, NOME), 
        DESCRICAO = @DESCRICAO, 
        DATA_INCLUSAO = ISNULL(@DATA_INCLUSAO, DATA_INCLUSAO), 
        DATA_ALTERACAO = @DATA_ALTERACAO 
    FROM 
        LOGIN_PERFIL_TB A 
    WHERE 
        A.LOGIN_PERFIL_ID = ISNULL(@LOGIN_PERFIL_ID, A.LOGIN_PERFIL_ID)

    EXEC LOGIN_PERFIL_SPS @LOGIN_PERFIL_ID 
END 
