CREATE PROCEDURE LOGIN_PERFIL_SPI 
    @NOME VARCHAR(50)  = NULL, 
    @DESCRICAO VARCHAR(500)  = NULL, 
    @DATA_INCLUSAO SMALLDATETIME = NULL, 
    @DATA_ALTERACAO SMALLDATETIME = NULL 
AS BEGIN 
 
    SET @DATA_INCLUSAO = ISNULL(@DATA_INCLUSAO, GETDATE()); 
 
    INSERT INTO LOGIN_PERFIL_TB ( 
        NOME, 
        DESCRICAO, 
        DATA_INCLUSAO, 
        DATA_ALTERACAO 
    ) VALUES ( 
        @NOME, 
        @DESCRICAO, 
        @DATA_INCLUSAO, 
        @DATA_ALTERACAO 
    ); 

    SELECT SCOPE_IDENTITY() AS LOGIN_PERFIL_ID; 
END 
