CREATE PROCEDURE LOGIN_PERFIL_SPS 
    @LOGIN_PERFIL_ID INT = NULL 
AS BEGIN 
    SELECT 
        A.LOGIN_PERFIL_ID, 
        A.NOME, 
        A.DESCRICAO, 
        A.DATA_INCLUSAO, 
        A.DATA_ALTERACAO 
    FROM 
        LOGIN_PERFIL_TB A 
    WHERE 
        A.LOGIN_PERFIL_ID = ISNULL(@LOGIN_PERFIL_ID, A.LOGIN_PERFIL_ID) 
END 
